# Generated by Django 2.2.5 on 2019-09-15 09:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=60)),
                ('color', models.CharField(default='black', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1000)),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
                ('correct_option', models.CharField(max_length=200)),
                ('hint', models.CharField(blank=True, max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.QuestionsTopic')),
                ('user', models.ForeignKey(on_delete=models.SET('Anonymus'), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField(default=False)),
                ('attempted', models.BooleanField(default=False)),
                ('Bookmark', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('score_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('like', models.BooleanField(default=False)),
                ('share', models.BooleanField(default=False)),
                ('report_question', models.BooleanField(default=False)),
                ('Last_action_date', models.DateTimeField(default=datetime.datetime.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Question')),
                ('user', models.ForeignKey(on_delete=models.SET('Anonymus'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
